"""Task 5: arena display payloads carry a machine-generated flag + attribution,
never generator identity (the anonymized-payload invariant stays intact)."""

from __future__ import annotations

import uuid

from app.database import SessionLocal
from app.main import _serialize
from app.models import Category, Comparison, Criterion, Generator, ModelOutput, Task
from app.seed import seed_all


def setup_module(_module):
    seed_all(force=True)


def test_serialize_flags_machine_generated_and_carries_attribution():
    with SessionLocal() as db:
        crit = db.query(Criterion).filter_by(slug="overall").one()
        cat = db.query(Category).first()
        gen = Generator(slug=f"g-{uuid.uuid4().hex}", name="g", kind="model", paradigm="p")
        db.add(gen)
        db.flush()
        task = Task(category_id=cat.id, title=f"t-{uuid.uuid4().hex[:8]}", prompt="p")
        db.add(task)
        db.flush()
        out_a = ModelOutput(
            task_id=task.id,
            generator_id=gen.id,
            asset_path="a.glb",
            asset_format="glb",
            source="api:fal:trellis",
            attribution="Generated by TRELLIS",
        )
        out_b = ModelOutput(
            task_id=task.id,
            generator_id=gen.id,
            asset_path="b.glb",
            asset_format="glb",
            source="bio3d-arena",
        )
        db.add_all([out_a, out_b])
        db.flush()
        comparison = Comparison(
            task_id=task.id,
            output_a_id=out_a.id,
            output_b_id=out_b.id,
            criterion_id=crit.id,
            session_id="test-sess",
        )
        db.add(comparison)
        db.flush()

        d = _serialize(comparison, task, crit, out_a, out_b)

        assert d["a"]["machine_generated"] is True
        assert d["a"]["attribution"] == "Generated by TRELLIS"
        assert d["b"]["machine_generated"] is False
        assert d["b"]["attribution"] is None
        assert "generator" not in d["a"] and "paradigm" not in d["a"]
        assert "generator" not in d["b"] and "paradigm" not in d["b"]
        db.rollback()
