"""Generate tomato 3D models via image-to-3D APIs from the canonical reference photo, and
ingest them as AI-reconstruction outputs. `generate_api_recon` is the testable core
(providers + env injected); `main()` wires the real reference image, PROVIDERS, and the
recon scorer. Commits per object. API keys come from env and are never logged.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select  # noqa: E402

from app import ingest  # noqa: E402
from app.models import Task  # noqa: E402

TOMATO_TITLE = "Solanum lycopersicum — single-image → 3D reconstruction"


def generate_api_recon(
    db, image_bytes, *, providers, env, score_fn=None, task_title=TOMATO_TITLE
) -> dict:
    task = db.execute(select(Task).where(Task.title == task_title)).scalars().first()
    if task is None:
        raise RuntimeError(f"subject task not found: {task_title!r}")
    report = {"generated": 0, "skipped_no_key": 0, "errors": 0, "by_provider": {}}
    for slug, (fn, env_var, name) in providers.items():
        key = env.get(env_var)
        if not key:
            report["skipped_no_key"] += 1
            continue
        try:
            glb = fn(image_bytes, api_key=key)
            out, _created = ingest.register_output(
                db,
                task_id=task.id,
                generator_slug=slug,
                generator_name=name,
                data=glb,
                ext="glb",
                title=f"{name} recon",
                meta={"depiction": "whole_plant", "provider": slug, "from_reference": "tomato_ref"},
            )
            out.source = f"api:{slug}"
            out.license = f"{name} generated-asset terms"
            out.attribution = f"Generated by {name} from CC reference photo"
            out.external_url = "https://platform.tripo3d.ai/" if slug == "tripo" else ""
            db.commit()  # provenance committed → hosted
            report["generated"] += 1
            report["by_provider"][slug] = report["by_provider"].get(slug, 0) + 1
            if score_fn is not None:
                try:
                    score_fn(db, out)
                    db.commit()
                except Exception as e:  # noqa: BLE001 — scoring best-effort; object stays hosted
                    print(f"  score failed for {out.id}: {e}")
                    db.rollback()
        except Exception as e:  # noqa: BLE001 — one provider never aborts the batch
            # Provider passes the key in a header, never in exception text, so str(e) is safe.
            print(f"  {slug} generation failed: {type(e).__name__}: {e}")
            report["errors"] += 1
            db.rollback()
    return report


def main() -> int:
    import os

    from app import recon_service
    from app.database import SessionLocal
    from app.image3d import PROVIDERS

    ref = Path(__file__).resolve().parent.parent / "data/assets/reference/tomato_ref.jpg"
    if not ref.exists():
        print(f"reference image missing: {ref} — source the CC photo first")
        return 1
    image_bytes = ref.read_bytes()
    active = {s: v for s, v in PROVIDERS.items() if os.environ.get(v[1])}
    if not active:
        print("no provider API key in env (e.g. TRIPO_API_KEY) — nothing to generate")
        return 0
    db = SessionLocal()
    try:
        report = generate_api_recon(
            db,
            image_bytes,
            providers=active,
            env=os.environ,
            score_fn=recon_service.score_and_store,
        )
        print(report)
    finally:
        db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
