"""Generate tomato 3D models via TEXT→3D APIs from a text prompt, and ingest them as AI outputs.
`generate_api_text` is the testable core (providers + env injected); `main()` wires the tomato
prompt, TEXT_PROVIDERS, and the recon scorer. Commits per object. API keys come from env and are
never logged.

Text→3D produces ORGAN/part-level meshes, not faithful whole plants (field-map verified) — these are
the generative-3D baseline the procedural path is measured against, flagged `modality=text` on ingest.
Key-gated: a live run needs FAL_KEY / REPLICATE_API_TOKEN.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select  # noqa: E402

from app import ingest  # noqa: E402
from app.models import Task  # noqa: E402

TOMATO_TITLE = "Solanum lycopersicum — single-image → 3D reconstruction"
TOMATO_PROMPT = (
    "A tomato plant, Solanum lycopersicum: an upright green stem with pinnately compound serrated "
    "green leaves and clusters of round red ripe tomatoes."
)


def _provenance(slug: str, name: str) -> tuple[str, str]:
    """(license, external_url) for an api: provider, derived from the slug prefix."""
    if slug.startswith("fal:"):
        url = "https://fal.ai"
    elif slug.startswith("replicate:"):
        url = "https://replicate.com"
    else:
        url = ""
    return f"{name} generated-asset terms (see provider)", url


def generate_api_text(
    db, prompt, *, providers, env, score_fn=None, task_title=TOMATO_TITLE
) -> dict:
    task = db.execute(select(Task).where(Task.title == task_title)).scalars().first()
    if task is None:
        raise RuntimeError(f"subject task not found: {task_title!r}")
    report = {"generated": 0, "skipped_no_key": 0, "errors": 0, "by_provider": {}}
    for slug, (fn, env_var, name) in providers.items():
        key = env.get(env_var)
        if not key:
            report["skipped_no_key"] += 1
            continue
        try:
            glb = fn(prompt, api_key=key)
            out, _created = ingest.register_output(
                db,
                task_id=task.id,
                generator_slug=slug,
                generator_name=name,
                data=glb,
                ext="glb",
                title=f"{name} (text→3D)",
                meta={
                    "depiction": "whole_plant",
                    "provider": slug,
                    "modality": "text",
                    "from_prompt": True,
                },
            )
            out.source = f"api:{slug}"
            out.license, out.external_url = _provenance(slug, name)
            out.attribution = f"Generated by {name} from a text prompt (text→3D, organ-level)"
            db.commit()  # provenance committed → hosted
            report["generated"] += 1
            report["by_provider"][slug] = report["by_provider"].get(slug, 0) + 1
            if score_fn is not None:
                try:
                    score_fn(db, out)
                    db.commit()
                except Exception as e:  # noqa: BLE001 — scoring best-effort; object stays hosted
                    print(f"  score failed for {out.id}: {e}")
                    try:
                        db.rollback()
                    except Exception:  # noqa: BLE001
                        pass
        except Exception as e:  # noqa: BLE001 — one provider never aborts the batch
            # Provider passes the key in a header, never in exception text, so str(e) is safe.
            print(f"  {slug} generation failed: {type(e).__name__}: {e}")
            report["errors"] += 1
            db.rollback()
    return report


def main() -> int:
    import os

    from app import recon_service
    from app.database import SessionLocal
    from app.image3d import TEXT_PROVIDERS

    active = {s: v for s, v in TEXT_PROVIDERS.items() if os.environ.get(v[1])}
    if not active:
        print(
            "no text→3D provider key in env (FAL_KEY / REPLICATE_API_TOKEN) — nothing to generate"
        )
        return 0
    db = SessionLocal()
    try:
        report = generate_api_text(
            db,
            TOMATO_PROMPT,
            providers=active,
            env=os.environ,
            score_fn=recon_service.score_and_store,
        )
        print(report)
    finally:
        db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
